version: '3.8'

services:
  orderer.blocktrace.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer.blocktrace.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_ADMIN_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/blocktrace.com/orderers/orderer.blocktrace.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/blocktrace.com/orderers/orderer.blocktrace.com/tls:/var/hyperledger/orderer/tls
      - ./configtx:/etc/hyperledger/fabric/configtx
      - orderer-data:/var/hyperledger/production
    ports:
      - "7050:7050"
      - "7053:7053"

  peer0.forensics.blocktrace.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.forensics.blocktrace.com
    environment:
      - CORE_PEER_ID=peer0.forensics.blocktrace.com
      - CORE_PEER_ADDRESS=peer0.forensics.blocktrace.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=ForensicsOrgMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.forensics:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=blocktrace-net
    volumes:
      - ./crypto-config/peerOrganizations/forensics.blocktrace.com/peers/peer0.forensics.blocktrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/forensics.blocktrace.com/peers/peer0.forensics.blocktrace.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/forensics.blocktrace.com/users:/etc/hyperledger/fabric/users
      - ./crypto-config/ordererOrganizations/blocktrace.com/orderers/orderer.blocktrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer/tlscacerts
      - ./configtx:/etc/hyperledger/fabric/configtx
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../chaincode/evidence:/opt/gopath/src/github.com/chaincode/evidence
    ports:
      - "7051:7051"
    depends_on:
      - couchdb.forensics

  couchdb.forensics:
    image: couchdb:3.3
    container_name: couchdb.forensics
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"

  peer0.police.blocktrace.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.police.blocktrace.com
    environment:
      - CORE_PEER_ID=peer0.police.blocktrace.com
      - CORE_PEER_ADDRESS=peer0.police.blocktrace.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_LOCALMSPID=PoliceOrgMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.police:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=blocktrace-net
    volumes:
      - ./crypto-config/peerOrganizations/police.blocktrace.com/peers/peer0.police.blocktrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/police.blocktrace.com/peers/peer0.police.blocktrace.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/police.blocktrace.com/users:/etc/hyperledger/fabric/users
      - ./crypto-config/ordererOrganizations/blocktrace.com/orderers/orderer.blocktrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer/tlscacerts
      - ./configtx:/etc/hyperledger/fabric/configtx
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../chaincode/evidence:/opt/gopath/src/github.com/chaincode/evidence
    ports:
      - "9051:9051"
    depends_on:
      - couchdb.police

  couchdb.police:
    image: couchdb:3.3
    container_name: couchdb.police
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"

  peer0.court.blocktrace.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.court.blocktrace.com
    environment:
      - CORE_PEER_ID=peer0.court.blocktrace.com
      - CORE_PEER_ADDRESS=peer0.court.blocktrace.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_LOCALMSPID=CourtOrgMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.court:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=blocktrace-net
    volumes:
      - ./crypto-config/peerOrganizations/court.blocktrace.com/peers/peer0.court.blocktrace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/court.blocktrace.com/peers/peer0.court.blocktrace.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/court.blocktrace.com/users:/etc/hyperledger/fabric/users
      - ./crypto-config/ordererOrganizations/blocktrace.com/orderers/orderer.blocktrace.com/msp/tlscacerts:/etc/hyperledger/fabric/orderer/tlscacerts
      - ./configtx:/etc/hyperledger/fabric/configtx
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../chaincode/evidence:/opt/gopath/src/github.com/chaincode/evidence
    ports:
      - "11051:11051"
    depends_on:
      - couchdb.court

  couchdb.court:
    image: couchdb:3.3
    container_name: couchdb.court
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9990:5984"

networks:
  default:
    name: blocktrace-net

volumes:
  orderer-data:
